### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by WandyLau** [bjornedstrom/python-sha3#7]
Just as I say.

**Comment by bjornedstrom** [comment]
Hello.

No it's not. Feel free to publish pull requests. :)

**Comment by WandyLau** [comment]
But as I can see the last commits is in 2016. And what is relationship between this project and pysha3? I am little confused.

**Comment by WandyLau** [comment]
And I got a problem when to install it on s390: 

**src/64/KeccakF-1600-opt64.c:250:2: error: #error "Not yet implemented".**

**Comment by bjornedstrom** [comment]
Yes, the last commit is from 2016. The library works for me and many others. If you have found a problem, I accept pull requests.

**Comment by WandyLau** [comment]
OK. So this error is raised because s390 is big endian. I will try to enable it then.

**Comment by WandyLau** [comment]
I got a patch for this, how can I push it? Push it directly to the master?
